packaging_format = 2

id = "torrelay"
name = "Tor relay"
description.en = "Defend Your Privacy! How To Create Your Own Tor Relay!"
description.fr = "Défendez votre vie privée ! Comment créer votre propre relais Tor !"

version = "0.4.8.10~ynh2"

maintainers = []

[upstream]
license = "BSD-3-Clause"
website = "https://www.torproject.org/"
admindoc = "https://community.torproject.org/relay/setup/bridge/debian-ubuntu/"
code = "https://github.com/torproject/tor"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "i386"]
multi_instance = false
ldap ="not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.contact]
    ask.en = "Choose an email address so we can contact you if there are problems with your bridge. This is optional but encouraged."
    ask.fr = "Choisissez une adresse e-mail afin que nous puissions vous contacter en cas de problème avec votre pont. Ceci est facultatif mais encouragé."
    type = "string"
    default = "address@email.com"

    [install.nickname]
    ask.en = "Pick a nickname that you like for your bridge. This is optional."
    ask.fr = "Choisissez un surnom que vous aimez pour votre pont. Ceci est facultatif."
    type = "string"
    default = "PickANickname"

[resources]

    [resources.ports]
    or.default = 9002
    or.exposed = "Both"
    obfs4.default = 9003
    obfs4.exposed = "Both"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    [resources.apt]
    packages = "apt-transport-https obfs4proxy"

    extras.tor.repo = "deb https://deb.torproject.org/torproject.org __YNH_DEBIAN_VERSION__ main"
    extras.tor.key = "https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc"
    extras.tor.packages = "tor tor-geoipdb deb.torproject.org-keyring"
